<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %> 
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Insert title here</title>
<style>
	table{
	margin-left:750px;
	}
</style>
</head>

<body>
<c:import url="main.jsp">

</c:import>
<table>
	<tr>
		<td>
			<ul>
				<li>이미지</li>
				<li>상품명</li>
				<li>가격</li>
			</ul>
		</td>
		<td>
			<ul>
				<li>이미지</li>
				<li>상품명</li>
				<li>가격</li>
			</ul>
		</td>	
		<td>
			<ul>
				<li>이미지</li>
				<li>상품명</li>
				<li>가격</li>
			</ul>
		</td>
	</tr>
	<tr>
		<td>
			<ul>
				<li>이미지</li>
				<li>상품명</li>
				<li>가격</li>
			</ul>
		</td>
		<td>
			<ul>
				<li>이미지</li>
				<li>상품명</li>
				<li>가격</li>
			</ul>
		</td>	
		<td>
			<ul>
				<li>이미지</li>
				<li>상품명</li>
				<li>가격</li>
			</ul>
		</td>
	</tr>
	<tr>
		<td>
			<ul>
				<li>이미지</li>
				<li>상품명</li>
				<li>가격</li>
			</ul>
		</td>
		<td>
			<ul>
				<li>이미지</li>
				<li>상품명</li>
				<li>가격</li>
			</ul>
		</td>	
		<td>
			<ul>
				<li>이미지</li>
				<li>상품명</li>
				<li>가격</li>
			</ul>
		</td>
	</tr>
</table>
</body>
</html>